# Generated by Django 5.2.6 on 2025-09-08 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='shop_views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
