# Generated by Django 5.2.6 on 2025-09-08 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_shop_shop_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='thumbnail',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='category',
            field=models.CharField(choices=[('transfer', 'Transfer'), ('update', 'Update'), ('exclusive', 'Exclusive'), ('match', 'Match'), ('rumor', 'Rumor'), ('analysis', 'Analysis')], default='update', max_length=50),
        ),
        migrations.AlterField(
            model_name='shop',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='shop',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
