# Generated by Django 5.2.6 on 2025-09-14 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_shop_thumbnail_alter_shop_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='shop_views',
            new_name='product_views',
        ),
        migrations.AlterField(
            model_name='shop',
            name='category',
            field=models.CharField(choices=[('New Item', 'New Item')], default='update', max_length=50),
        ),
    ]
